// Định nghĩa các thể loại
export enum Category {
  HOME = 'home',
  THOI_SU = 'thoi-su',
  QUOC_TE = 'quoc-te',
  LAO_DONG = 'lao-dong',
  BAN_DOC = 'ban-doc',
  KINH_TE = 'kinh-te',
  SUC_KHOE = 'suc-khoe',
  GIAO_DUC = 'giao-duc-khoa-hoc',
  PHAP_LUAT = 'phap-luat',
  VAN_HOA_VAN_NGHE = 'van-hoa-van-nghe',
  GIAI_TRI = 'giai-tri',
  CONG_NGHE = 'cong-nghe',
  DU_LICH_XANH = 'du-lich-xanh',
  PHU_NU = 'phu-nu',
  GIA_DINH = 'gia-dinh',
  DIA_OC = 'dia-oc',
  HOI_NONG_DAP_NHANH = 'hoi-nong-dap-nhanh',
  TRUY_VET_MANG_XA_HOI = 'truy-vet-mang-xa-hoi',
  NOI_THANG = 'noi-thang',
  GOC_NHIN = 'goc-nhin',
  TRICH_DAN_NONG = 'trich-dan-nong',
  VI_TUYEN_DAU_CHONG_DICH = 'vi-tuyen-dau-chong-dich',
  VUNG_MIEN = 'vung-mien',
  DOC_QUYEN = 'doc-quyen',
  KHOA_HOC = 'khoa-hoc',
  MAI_VANG = 'mai-vang',
  DOI_SONG = 'doi-song',
  TU_HAO_CO_TO_QUOC = 'tu-hao-co-to-quoc',
  DU_LICH = 'du-lich',
  CHUYEN_TU_NOI_CACH_LY = 'chuyen-tu-noi-cach-ly',
  BIEN_DAO = 'bien-dao',
  VIDEO = 'video',
  THI_TRUONG = 'thi-truong',
  LY_TUONG_SONG = 'ly-tuong-song',
  DONG_TIEN_THONG_MINH = 'dong-tien-thong-minh',
  MOI_TRUONG = 'moi-truong',
  TU_HAO_HANG_VIET = 'tu-hao-hang-viet',
  KET_QUA_SO_XO = 'ket-qua-so-xo',
  NGUOI_VIET_YEU_SU_VIET = 'nguoi-viet-yeu-su-viet',
  THE_THAO = 'the-thao',
  NULL = '',
}

export const categoryName = {
  [Category.HOME]: 'Trang chủ',
  [Category.THOI_SU]: 'Thời sự',
  [Category.QUOC_TE]: 'Quốc tế',
  [Category.LAO_DONG]: 'Lao động',
  [Category.KINH_TE]: ' Kinh tế',
  [Category.BAN_DOC]: 'Bạn đọc',
  [Category.SUC_KHOE]: 'Sức khỏe',
  [Category.GIAO_DUC]: 'Giáo dục',
  [Category.PHAP_LUAT]: 'Pháp luật',
  [Category.VAN_HOA_VAN_NGHE]: 'Văn hóa - Văn nghệ',
  [Category.GIAI_TRI]: 'Giải trí',
  [Category.THE_THAO]: 'Thể thao',
  [Category.CONG_NGHE]: 'Công nghệ',
  [Category.DU_LICH_XANH]: 'Du lịch xanh',
  [Category.PHU_NU]: 'Phụ nữ',
  [Category.GIA_DINH]: 'Gia đình',
  [Category.DIA_OC]: 'Địa ốc',
  [Category.HOI_NONG_DAP_NHANH]: 'Hội nông dân nhanh',
  [Category.TRUY_VET_MANG_XA_HOI]: 'Truyền thông mạng xã hội',
  [Category.NOI_THANG]: 'Nói thẳng',
  [Category.GOC_NHIN]: 'Góc nhìn',
  [Category.TRICH_DAN_NONG]: 'Trích dẫn nóng',
  [Category.VI_TUYEN_DAU_CHONG_DICH]: 'Vỉ tuyến đầu chống dịch',
  [Category.VUNG_MIEN]: 'Vùng miền',
  [Category.DOC_QUYEN]: 'Độc quyền',
  [Category.KHOA_HOC]: 'Khoa học',
  [Category.MAI_VANG]: 'Mai vàng',
  [Category.DOI_SONG]: 'Đời sống',
  [Category.TU_HAO_CO_TO_QUOC]: 'Tự hào có tổ quốc',
  [Category.DU_LICH]: 'Du lịch',
  [Category.CHUYEN_TU_NOI_CACH_LY]: 'Chuyện từ nơi cách ly',
  [Category.BIEN_DAO]: 'Biển đảo',
  [Category.VIDEO]: 'Video',
  [Category.THI_TRUONG]: 'Thị trường',
  [Category.LY_TUONG_SONG]: 'Lý tưởng sống',
  [Category.DONG_TIEN_THONG_MINH]: 'Đồng tiền thông minh',
  [Category.MOI_TRUONG]: 'Môi trường',
  [Category.TU_HAO_HANG_VIET]: 'Tự hào hàng Việt',
  [Category.KET_QUA_SO_XO]: 'Kết quả số xổ',
  [Category.NGUOI_VIET_YEU_SU_VIET]: 'Người Việt yêu sử Việt',
  [Category.NULL]: '',
};
